config/routes.rb
Ajaxtodo::Application.routes.draw do
  root to: 'home#index'
  #Notice that I am only including the resourceful routes that I am using, not all seven
  #index is only included because it appears to be necessary for form_for in some cases
  resources :tasks, only: [:new, :index, :create, :destroy, :update] do
    member do 
      put :moveup
      put :movedown
    end
  end
  resources :priorities, only: [:new, :index, :create]
end

app/models/priority.rb
class Priority < ActiveRecord::Base
  attr_accessible :name, :urgency_index, :color, :task_ids

  has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :name, :desc, :duedate, :priority_id

  belongs_to :priority

  def increase_urgency
    self

    # priority.where
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/priorities_controller.rb
class PrioritiesController < ApplicationController
  def new
    @priority = Priority.new
    @priorities = Priority.all
  end
  def create
    priority = Priority.new(params[:priority])
    priority.save!
    #Instead of rendering text, I render JSON so that the priority and all of its attributes are available
    #in the data variable in my javascript callback function
    render json: priority
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task = Task.new
    @tasks = Task.joins(:priority).order('priorities.urgency_index DESC, name ASC' )
    @priorities = Priority.all
  end

  def create
    task = Task.new(params[:task])
    task.save!
    #Instead of rendering text, I render JSON so that the task and all of its attributes are available
    #in the data variable in my javascript callback function
    render json: {task: task, priority: task.priority}
  end

  def destroy
    #1 - get the ID of the item we wish to destroy
    task = Task.find(params[:id])
    # 2 - delete the item with that ID from the DB
    task.destroy
    # 3 - render some sort of response or redirect
    render json: task
  end  

  def update
    task = Task.find(params[:id])
    task.update_attributes(params[:task])

    render json: {task: task, priority: task.priority}
  end

  def move(array_shift)
    # id = params[:id]
    task = Task.find(params[:id])
    priorities = Priority.order(:urgency_index)
    urgency_index_array = priorities.map{|p| p.urgency_index}
    urgency_index_array = urgency_index_array.uniq
    # priority = task.priority.urgency_index

  end

  def moveup
    # data = arrow(1)
    # data = "funions"
    task = Task.find(params[:id])

    task.increase_urgency

    render json: {task: task, priority: task.priority}

    # render text: 'moveup method!!'
  end


  def movedown
    # data = arrow(-1)
    # render json: data
    puts 'move up method!'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
Home

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Ajaxtodo
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag "ui-extra", :src => 'http://code.jquery.com/ui/1.10.3/jquery-ui.js'
    = csrf_meta_tags
  %body
    .row
      = render partial: '/layouts/partials/nav'
      = yield
    / Foundation initialization javascript
    :javascript
      $(document).foundation();

app/views/layouts/partials/_nav.html.haml
%nav.top-bar
  %ul.title-area
    / Title Area
    %li.name
      %h1
        =link_to 'ToDo', root_path
    / Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone
    %li.toggle-topbar.menu-icon
      %a{:href => "#"}
        %span Menu
  %section.top-bar-section
    / Left Nav Section
    %ul.left
      %li.divider
      %li
        =link_to 'Priorities', new_priority_path
      %li.divider
      %li
        =link_to 'Tasks', new_task_path
      %li.divider

app/views/priorities/new.html.haml
= form_for @priority do |f|
  = f.label :name
  = f.text_field :name
  = f.label :urgency_index
  = f.number_field :urgency_index
  = f.label :color
  = f.text_field :color
  / %input#priority_color{type: 'color', name: 'priority[color]'}
  - Task.all.each do |task|
    = check_box_tag "priority[task_ids][]", task.id, @priority.tasks.include?(task)
    = task.name
  /= f.collection_select :task_ids, Task.all, :id, :name, {:include_blank => true}, {multiple: true}
  = f.submit id: 'submit'

%table#priorities
  %thead
    %tr
      %th Name
      %th Urgency Index
      %th Color
      %th Color
  %tbody
    - @priorities.each do |priority|
      %tr
        %td
          = priority.name
        %td
          = priority.urgency_index
        %td
          = priority.color
        %td{style: "background-color: #{priority.color}"}

= javascript_include_tag 'priorities'

app/views/tasks/new.html.haml
= form_for @task do |f|
  = f.label :name
  = f.text_field :name
  = f.label :desc
  = f.text_field :desc
  = f.label :duedate
  = f.text_field :duedate
  = f.label :priority_id
  / = f.select :priority_id, Priority.all.map{|priority| [priority.name, priority.id]}, :include_blank => true, :prompt => "-- Choose Priority --"
  = f.collection_select :priority_id, @priorities, :id, :name, include_blank: true, prompt: '-- Choose Priority --'
  = f.submit id: 'submit', class: 'button success small'
  = f.submit id: 'edit-submit', class: 'button small hidden', value: 'Update Task'

%table#tasks
  %thead
    %tr
      %th
        Move Task
      %th
        = link_to 'Name', '#', id: 'name-sort'
      %th
        = link_to 'Desc', '#', id: 'desc-sort'
      %th
        = link_to 'Duedate', '#', id: 'duedate-sort'
      %th
        = link_to 'Options', '#', id: 'options-heading'
  %tbody
    - @tasks.each do |task|
      %tr{:'data-id' => task.id, style: "background-color: #{task.priority.color}"}
        %td.movement  
          %i
            =link_to '', '#', class: 'up-arrow general foundicon-up-arrow'
          %i
            =link_to '', '#"', class: 'down-arrow general foundicon-down-arrow'
        %td.name
          = task.name
        %td.desc
          = task.desc
        %td.duedate
          = task.duedate
        %td.urgency-index{style: 'display: none;'}
          = task.priority.urgency_index
        %td.priority_id{style: 'display: none;'}
          = task.priority.id
        %td.options
          / = link_to 'View', '#', {class: 'small button'}
          / = link_to 'Delete', '#', {class: 'small button delete-button', method: 'delete'}
          %a{href: '#', :'data-id' => task.id, class: 'small button delete-button'} Delete
          = link_to 'Edit', '#', class: 'button edit-button small info', :'data-id' => task.id

= javascript_include_tag 'tasks'